Repository makarovaiuliia/kickflip, pull requests merged in 2024-05, with the labels that each got.

#44 RSS-ECOMM-3-06/07 Interactive product cards, Redirect to detailed product page
  kickFlip-project/src/components/app/app.tsx
  kickFlip-project/src/components/card/card.css
  kickFlip-project/src/components/card/card.tsx
  kickFlip-project/src/components/card/mockData.ts
  kickFlip-project/src/components/header/header.tsx
  kickFlip-project/src/types/types.ts
  kickFlip-project/src/utils/utils.ts
Labels: Design

#49 feat/RSS-ECOMM-3_09: Fetch and Display Product Details using Commercetools API
  kickFlip-project/src/components/app/app.tsx
  kickFlip-project/src/components/product/product.css
  kickFlip-project/src/components/product/product.tsx
  kickFlip-project/src/components/product/productDetails/productDescr.tsx
  kickFlip-project/src/components/product/productDetails/productDetailsContainer.tsx
  kickFlip-project/src/components/product/productDetails/productInfo.tsx
  kickFlip-project/src/components/product/productDetails/productSizes.tsx
  kickFlip-project/src/components/product/productDetails/productVariantsImages.tsx
  kickFlip-project/src/components/product/productImages/imagesContainer.tsx
  kickFlip-project/src/components/product/productImages/mainImage.tsx
  kickFlip-project/src/components/product/productImages/sideImage.tsx
  kickFlip-project/src/main.css
  kickFlip-project/src/pages/product/productPage.tsx
  kickFlip-project/src/types/componentsInterfaces.ts
  kickFlip-project/src/types/types.ts
  kickFlip-project/src/utils/kickflip-api.ts
  kickFlip-project/src/utils/utils.ts
Labels: Frontend

#48 RSS ECOMM 3-01/02 Fetch and display product list & Display prices with discount
  kickFlip-project/src/components/app/app.tsx
  kickFlip-project/src/components/card/card.css
  kickFlip-project/src/components/card/card.tsx
  kickFlip-project/src/components/card/mockData.ts
  kickFlip-project/src/components/cardList/cardList.css
  kickFlip-project/src/components/cardList/cardList.tsx
  kickFlip-project/src/components/header/header.tsx
  kickFlip-project/src/pages/products/productsPage.tsx
  kickFlip-project/src/services/sneakersSlice.ts
  kickFlip-project/src/services/store.ts
  kickFlip-project/src/types/types.ts
  kickFlip-project/src/utils/kickflip-api.ts
Labels: Frontend

#51 RSS-ECOMM-3-08 Implement category and breadcrumb navigation
  kickFlip-project/src/components/app/app.tsx
  kickFlip-project/src/components/breadCrumbs/breadCrumbs.css
  kickFlip-project/src/components/breadCrumbs/breadCrumbs.tsx
  kickFlip-project/src/components/cardList/cardList.tsx
  kickFlip-project/src/components/categorySection/categorySection.css
  kickFlip-project/src/components/categorySection/categorySection.tsx
  kickFlip-project/src/components/layout/basicLayout.css
  kickFlip-project/src/data/categoryData.ts
  kickFlip-project/src/pages/products/productsPage.css
  kickFlip-project/src/pages/products/productsPage.tsx
  kickFlip-project/src/services/sneakersSlice.ts
  kickFlip-project/src/types/types.ts
  kickFlip-project/src/utils/kickflip-api.ts
  kickFlip-project/src/utils/utils.ts
Labels: Backend connection, Frontend

#50 Feat/RSS-ECOMM-3_09
  kickFlip-project/src/components/app/app.tsx
  kickFlip-project/src/components/layout/basicLayout.css
  kickFlip-project/src/components/loader/loader.css
  kickFlip-project/src/components/loader/loader.tsx
  kickFlip-project/src/main.css
  kickFlip-project/src/pages/product/productPage.tsx
  kickFlip-project/src/utils/kickflip-api.ts
Labels: Frontend
